{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "myapp-helm.fullname" . }}
spec:
  rules:
    - host: "{{ (index .Values.ingress.hosts 0).host }}"
      http:
        paths:
          - path: "{{ (index (index .Values.ingress.hosts 0).paths 0).path }}"
            pathType: Prefix
            backend:
              service:
                name: {{ include "myapp-helm.fullname" . }}
                port:
                  number: 80
{{- end }}
