apiVersion: v1
kind: Secret
metadata:
  name: perchases-secret
  namespace: prod
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQ=   # "password" base64
  API_KEY: YXBpa2V5MTIz        # "apikey123" base64
