apiVersion: v1
kind: Service
metadata:
  name: perchases-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: perchases
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}

