apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp-helm.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
  selector:
    app: {{ include "myapp-helm.name" . }}
