apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
        - name: orderservice
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}

          env:
            - name: APP_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: orderservice-config
                  key: APP_MESSAGE

            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: orderservice-config
                  key: APP_ENV

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orderservice-secret
                  key: DB_PASSWORD

            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: orderservice-secret
                  key: API_KEY

          volumeMounts:
            - name: orderservice-storage
              mountPath: /data

      volumes:
        - name: orderservice-storage
          persistentVolumeClaim:
            claimName: {{ .Values.pvcName }}

