namespace: prod

ingress:
  enabled: true
  className: nginx

  # ---- MULTIPLE HOSTS ----
  hosts:
    - host: myapp.local
      paths:
        - path: /myapp
          service: myapp-service
          port: 8080
        - path: /orderservice
          service: orderservice-service
          port: 8000

    - host: perchases.local
      paths:
        - path: /
          service: perchases-service
          port: 8091

  # ---- TLS (optional) ----
  tls: []
  # Example:
  # tls:
  #   - hosts:
  #       - myapp.local
  #     secretName: ingress-tls-secret

