apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../apps/app1/overlays/staging
  - ../../apps/app2/overlays/staging
commonLabels:
  cluster: staging
